# Generated by Django 4.0.5 on 2022-08-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('task_desc', models.TextField(blank=True)),
                ('task_pub_date', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapi.taskprogress')),
            ],
        ),
    ]
